<?php

$response = [
    "object" => "payment",
    "id" => "pay_c3usakj51fpf33rb",
    "dateCreated" => "2023-12-27",
    "customer" => "cus_000005824295",
    "installment" => "1a216d2c-4adb-42b0-848e-ff07a10f9e9f",
    "paymentLink" => null,
    "value" => 15,
    "netValue" => 14.39,
    "originalValue" => null,
    "interestValue" => null,
    "description" => "Parcela 1 de 2.",
    "billingType" => "CREDIT_CARD",
    "confirmedDate" => "2023-12-27",
    "creditCard" => [
        "creditCardNumber" => "8829",
        "creditCardBrand" => "MASTERCARD",
        "creditCardToken" => "cd2199af-555e-4f25-a6cb-e122d0901aaf",
    ],
    "pixTransaction" => null,
    "status" => "CONFIRMED",
    "dueDate" => "2023-12-30",
    "originalDueDate" => "2023-12-30",
    "paymentDate" => null,
    "clientPaymentDate" => "2023-12-27",
    "installmentNumber" => 1,
    "invoiceUrl" => "https://sandbox.asaas.com/i/c3usakj51fpf33rb",
    "invoiceNumber" => "04828634",
    "externalReference" => null,
    "deleted" => false,
    "anticipated" => false,
    "anticipable" => false,
    "creditDate" => "2024-01-29",
    "estimatedCreditDate" => "2024-01-29",
    "transactionReceiptUrl" => "https://sandbox.asaas.com/comprovantes/1984886699597064",
    "nossoNumero" => null,
    "bankSlipUrl" => null,
    "lastInvoiceViewedDate" => null,
    "lastBankSlipViewedDate" => null,
    "discount" => [
        "value" => 0.0,
        "limitDate" => null,
        "dueDateLimitDays" => 0,
        "type" => "FIXED",
    ],
    "fine" => [
        "value" => 0.0,
        "type" => "FIXED",
    ],
    "interest" => [
        "value" => 0.0,
        "type" => "PERCENTAGE",
    ],
    "postalService" => false,
    "custody" => null,
    "refunds" => null,
];
