<?php

return  [
  "name" => "Teste Usuario",
  "cpfCnpj" => "298.051.248-60",
  "email" => "test@example.net",
  "phone" => "164817-4065",
  "mobilePhone" => "1696351-8553",
  "address" => " R. Cristiana",
  "addressNumber" => 810,
  "complement" => "",
  "province" => "Galvão do Leste",
  "postalCode" => "41420-665",
  "externalReference" => "",
  "notificationDisabled" => false,
  "additionalEmails" => "",
  "municipalInscription" => "",
  "stateInscription" => "",
  "observations" => "Generated by faker test",
  "groupName" => "Tests",
  "company" => "Romero Comercial Ltda."
];