<?php

$response = [
    "object" => "payment",
    "id" => "pay_j875qgxq8ycbl42i",
    "dateCreated" => "2023-12-27",
    "customer" => "cus_000005824295",
    "paymentLink" => null,
    "value" => 49.9,
    "netValue" => 48.91,
    "originalValue" => null,
    "interestValue" => null,
    "description" => null,
    "billingType" => "BOLETO",
    "canBePaidAfterDueDate" => true,
    "pixTransaction" => null,
    "status" => "PENDING",
    "dueDate" => "2023-12-30",
    "originalDueDate" => "2023-12-30",
    "paymentDate" => null,
    "clientPaymentDate" => null,
    "installmentNumber" => null,
    "invoiceUrl" => "https://sandbox.asaas.com/i/j875qgxq8ycbl42i",
    "invoiceNumber" => "04827444",
    "externalReference" => null,
    "deleted" => false,
    "anticipated" => false,
    "anticipable" => false,
    "creditDate" => null,
    "estimatedCreditDate" => null,
    "transactionReceiptUrl" => null,
    "nossoNumero" => "1379674",
    "bankSlipUrl" => "https://sandbox.asaas.com/b/pdf/j875qgxq8ycbl42i",
    "lastInvoiceViewedDate" => null,
    "lastBankSlipViewedDate" => null,
    "discount" => [
        "value" => 0.0,
        "limitDate" => null,
        "dueDateLimitDays" => 0,
        "type" => "FIXED",
    ],
    "fine" => [
        "value" => 0.0,
        "type" => "FIXED",
    ],
    "interest" => [
        "value" => 0.0,
        "type" => "PERCENTAGE",
    ],
    "postalService" => false,
    "custody" => null,
    "refunds" => null,
];
